services:
  frontend:
    build: "frontend"
    ports:
      - "2000:2000"

  backend:
    build: "backend"
    ports:
      - "3000:3000"
    depends_on:
      - db
      -
  db:
    image: "18.1-alpine"
    ports:
      - "5432:5432"
    environment:
      - ""
    volumes:
      - ""

