services:
  frontend:
    build: "frontend"
    ports:
      - "2000:2000"

  backend:
    build: "backend"
    ports:
      - "3000:3000"
    depends_on:
      - "postgresql"

  postgresql:
    image: "18.1-alpine"
    ports:
      - "5432:5432"
    volumes:
      - "postgresql:var/lib/postgresql"

