services:

  backend:
    container_name: "backend"
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.development
    develop:
      watch:
        - action: sync
          path: ./backend/
          target: /app/
          ignore:
            - node_modules/
            - uploads/
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/yarn.lock
          action: rebuild
    volumes:
      - "./backend/uploads:/app/uploads"
    depends_on:
      - postgres_db

  postgres_db:
    container_name: "postgres"
    image: "postgres:17-alpine"
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env.development
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "postgres:/var/lib/postgresql/data"

volumes:
  postgres:
  uploads:
