services:

  backend:
    container_name: "backend"
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"

    develop:
      watch:
        - action: sync
<<<<<<< HEAD
          path: ./backend/
          target: /app/
=======
          path: ./backend/src
          target: ./app

>>>>>>> 2151454ad1b519ca6c709abdfbde62dc0c2c8a12
        - action: rebuild
          path: package.json
    depends_on:
      - postgres

  postgres:
    container_name: "postgres"
    image: "postgres:18-alpine"
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env.development
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "postgres:/var/lib/postgresql/data"

volumes:
  backend:
  postgres:
