FROM node:20-alpine AS production

WORKDIR /app

COPY package.json yarn.lock ./app/

RUN yarn workspaces focus --all --production

COPY  ./dest /app/dest

EXPOSE 5000

CMD ["yarn", "backend:start:prod"]
