FROM node:20-alpine AS development

WORKDIR /app

COPY package.json tsconfig.json tsconfig.build.json yarn.lock /app/
COPY ./dist /app/dist

RUN yarn global add @nestjs/cli

RUN yarn install

COPY ./src /app/src

# Settings hot reload
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

CMD ["yarn", "backend:start:dev"]

