FROM node:24-alpine AS development

WORKDIR /app

COPY package.json tsconfig.json tsconfig.build.json yarn.lock /app/

RUN yarn install

COPY ./src /app/src

# Settings hot reload
ENV CHOKIDAR_USEPOLLING=true

CMD ["yarn", "backend:start:dev"]

