name: CI for project "FROGO"
run-name: Project FROGO

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: yarn install

