name: CI for project "FROGO"
run-name: Project FROGO

on:
  push:

jobs:
  initialization:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.20.0]

    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing yarn
        run: sudo apt install yarn
